version: "3.9"

services:
  ecommerce_app:
    container_name: ecommerce_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - ecommerce_db
    expose:
      - 8000
    networks:
      - ecommerce_network

  ecommerce_db:
    container_name: ecommerce_db
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    expose:
      - 5433
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
